services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - kg-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  wait-for-neo4j:
    image: busybox
    container_name: wait-for-neo4j
    depends_on:
      neo4j:
        condition: service_healthy
    command: sleep 15
    networks:
      - kg-network

  kg-builder:
    build:
      context: .
      dockerfile: build/builder/Dockerfile
    container_name: kg-builder
    ports:
      - "5002:5000"
    depends_on:
      - wait-for-neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - LLM_URL=http://host.docker.internal:11434/api/generate
      - LLM_MODEL=qwen2.5:3b
    volumes:
      - ./cache/builder:/app/cache
      - ./config/builder.yaml:/app/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kg-network

  kg-enricher:
    build:
      context: .
      dockerfile: build/enricher/Dockerfile
    container_name: kg-enricher
    ports:
      - "5003:5001"
    depends_on:
      - wait-for-neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - LLM_URL=http://host.docker.internal:11434/api/generate
      - LLM_MODEL=qwen2.5:3b
      - ENRICHER_BATCH_SIZE=10
      - ENRICHER_INTERVAL_SECONDS=60
      - ENRICHER_MAX_RELATIONSHIPS=100
      - ENRICHER_CONCURRENCY=5
    volumes:
      - ./cache/enricher:/app/cache
      - ./config/enricher.yaml:/app/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kg-network

  kg-frontend:
    build:
      context: ./kg-frontend
      dockerfile: Dockerfile
    container_name: kg-frontend
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
      - kg-builder
      - kg-enricher
    networks:
      - kg-network

networks:
  kg-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: 