services:
  neo4j:
    image: neo4j:4.4
    container_name: kaygeego-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - kaygeego-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  wait-for-neo4j:
    image: busybox
    container_name: kaygeego-wait-for-neo4j
    depends_on:
      neo4j:
        condition: service_healthy
    command: sleep 15
    networks:
      - kaygeego-network

  api-server:
    build:
      context: ./kg-builder
      dockerfile: ./cmd/api-server/Dockerfile
    image: kaygeego-api-server
    container_name: kaygeego-api-server
    ports:
      - "5001:5000"
    depends_on:
      - wait-for-neo4j
    environment:
      - API_PORT=5000
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app/project
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kaygeego-network

  builder:
    build:
      context: ./kg-builder
    image: kaygeego-builder
    container_name: kaygeego-builder-main
    ports:
      - "5002:5000"
    depends_on:
      - wait-for-neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - LLM_URL=http://host.docker.internal:11434/api/generate
      - LLM_MODEL=phi4:latest
      - SEED_CONCEPT=${SEED_CONCEPT:-Artificial Intelligence}
      - MAX_NODES=${MAX_NODES:-100}
      - TIMEOUT_MINUTES=${TIMEOUT_MINUTES:-30}
      - RANDOM_RELATIONSHIPS=${RANDOM_RELATIONSHIPS:-20}
      - CONCURRENCY=${CONCURRENCY:-5}
    volumes:
      - ./kg-builder/cache:/app/cache
      - ./kg-builder/config.yaml:/app/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kaygeego-network
    command: sh -c "/app/api-server & /kg-builder"

  enricher:
    build:
      context: ./kg-enricher
    image: kaygeego-enricher
    container_name: kaygeego-enricher
    ports:
      - "5003:5001"
    depends_on:
      - wait-for-neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - LLM_URL=http://host.docker.internal:11434/api/generate
      - LLM_MODEL=phi4:latest
      - ENRICHER_BATCH_SIZE=10
      - ENRICHER_INTERVAL_SECONDS=60
      - ENRICHER_MAX_RELATIONSHIPS=50
      - ENRICHER_CONCURRENCY=5
    volumes:
      - ./kg-enricher/cache:/app/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kaygeego-network
    command: sh -c "/app/api-server & /kg-enricher"

  frontend:
    image: nginx:alpine
    container_name: kaygeego-frontend
    ports:
      - "8080:80"
    volumes:
      - ./kg-frontend/public:/usr/share/nginx/html
      - ./kg-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - neo4j
      - builder
      - enricher
      - api-server
    networks:
      - kaygeego-network

networks:
  kaygeego-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: 