# Knowledge Graph Builder Configuration

# Neo4j Configuration
neo4j:
  uri: "bolt://neo4j:7687"
  user: "neo4j"
  password: "password"
  max_retries: 5
  retry_interval_seconds: 5

# LLM Configuration
llm:
  url: "http://host.docker.internal:11434/api/generate"
  model: "phi4:latest"  # Changed to phi4:latest
  cache_dir: "./cache/llm"

# Graph Configuration
graph:
  seed_concept: "Machine Learning"
  max_nodes: 100
  timeout_minutes: 30
  worker_count: 5
  random_relationships: 20
  concurrency: 5