# Knowledge Graph Builder Configuration

# Neo4j Configuration
neo4j:
  uri: "bolt://neo4j:7687"
  user: "neo4j"
  password: "password"
  max_retries: 5
  retry_interval_seconds: 5

# LLM Configuration
llm:
  url: "http://host.docker.internal:11434/api/generate"
  model: "qwen2.5:3b"  # Changed from llama3.1:latest to qwen2.5:3b
  cache_dir: "./cache/llm"

# Graph Configuration
graph:
  seed_concept: "Artificial Intelligence"
  max_nodes: 850
  timeout_minutes: 30
  worker_count: 10
  random_relationships: 50
  concurrency: 5 