version: '3'

services:
  neo4j-test:
    image: neo4j:4.4
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      - kg-test-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kg-builder-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      neo4j-test:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j-test:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - LLM_URL=http://host.docker.internal:11434/api/generate
      - LLM_MODEL=llama3.1:latest
      - LLM_CACHE_DIR=/app/cache
    volumes:
      - ./:/app
      - ./test-cache:/app/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kg-test-network
    command: go test -v ./internal/... ./cmd/...

networks:
  kg-test-network:
    driver: bridge 